### ISSUE TITLE
ERROR in TruncateModule is not an NgModule

### ISSUE THREAD

**Issue by chetanrana2702** [yellowspot/ng2-truncate#18]
I am getting this issue when did the ng serve. but i do not think it was installed properly

`-- ng2-truncate@1.3.4 
  +-- UNMET PEER DEPENDENCY @angular/animations@4.0.1
  +-- UNMET PEER DEPENDENCY @angular/common@4.0.1
  +-- UNMET PEER DEPENDENCY @angular/compiler@4.0.1
  +-- UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
  `-- UNMET PEER DEPENDENCY zone.js@^0.8.4

**Comment by cristianstu** [comment]
is the issue solved?
What was the problem?
