### ISSUE TITLE
Param for counting '...' as character before trunc. calc.

### ISSUE THREAD

**Issue by igoramidzic** [yellowspot/ng2-truncate#28]
A nice-to-have would be the ability to toggle whether the truncating character, ex: '...', counts as one character before the truncation calculation.

Helps avoid:
`{{ user.email | truncate : 16 }}` -> `example@gmail.co...`
where `...` is longer than `m`

`example@gmail.co...`, counting '...' as 1 character, equals 17 characters total.

Maybe take the truncate parameter `16` + 1, then truncate?

**Comment by cristianstu** [comment]
I think we can use the trailing string length, it is actually 1 not 3 by default, the three dots is actually a single character.
