### ISSUE TITLE
Truncate HTML content

### ISSUE THREAD

**Issue by zolakt** [yellowspot/ng2-truncate#30]
Is there any way to truncate HTML content?
I have content generated with TinyMCE and it contains generated elements and styles, like:

`<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: ''Open Sans'', Arial, sans-serif;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pellentesque odio nec sollicitudin accumsan. Donec congue porta metus ut tempus. In in tristique libero. Praesent quam eros, aliquet ac felis sed, eleifend mollis dolor. Aenean tempor finibus massa, sit amet vehicula ipsum facilisis eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam facilisis mauris laoreet felis sodales sodales. Sed imperdiet fringilla libero, non euismod tortor elementum eget. In purus erat, imperdiet eu lacus eu, consectetur cursus dui.</p>`

So if I set "words : 5" for example, it will return an empty string.

**Comment by cristianstu** [comment]
Currently we do not support this. Truncate html is out of scope so far.
