### ISSUE TITLE
Cannot run tests: Unexpected token export

### ISSUE THREAD

**Issue by darkbasic** [yellowspot/ng2-truncate#35]
```
  ● Test suite failed to run

    /home/niko/WebstormProjects/digital_services/WebApp/packages/client/node_modules/@yellowspot/ng-truncate/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { TruncateModule, TRUNCATE_PIPES } from './truncate.module';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token export

      17 | import { TruncateModule } from '@yellowspot/ng-truncate';
```

**Comment by cristianstu** [comment]
How are running the tests?
Which version of node are you using?

**Comment by darkbasic** [comment]
I think the issue lies in the packaging, but I switched to a pure CSS solution so I didn't check any further:
```
      mat-panel-description {
        overflow: hidden;

        a {
          overflow: hidden;
          white-space: nowrap;
          text-overflow: ellipsis;
        }
      }
```
There is also another library which among other things does truncation and just works, but I don't remember the name.

**Comment by cristianstu** [comment]
I have the tests running on projetcs using this lib, but we probably need to switch to the angular-cli/ng-packager to create the bundles and avoid conflict in different environments.

I've created https://github.com/yellowspot/ng2-truncate/issues/37 to follow updates on this.

Personally, I think always a clean css solution when it is possible, is better than using a library. So if it works for your project, go with that instead!

**Comment by darkbasic** [comment]
I do like ng-packagr alot, so I strongly advice you to do so. Migration will be very straightforward.

**Comment by johnhamm** [comment]
CSS isn't always an available option:

`<div title="SomeReallyLongString | truncate:100"></div>
`
