### ISSUE TITLE
truncate does not work  when using with other library

### ISSUE THREAD

**Issue by cikcoh** [yellowspot/ng2-truncate#41]
After adding https://www.npmjs.com/package/angular-linky and 
https://www.npmjs.com/package/nl2br-pipe like this;

`<p  [innerHTML]="n.notes| linky | nl2br : true ">{{n.notes | truncate :300: "..."}} <span *ngIf="n.notes.length > 300" (click)="detail(i)"><b>see more</b></span></p>`

my text does not truncate anymore? and im not sure where to start debugging because there is no error. 

Kindly help me on this matter. Thanks

**Comment by cristianstu** [comment]
I think it is working, but you are replacing the truncated text setting `innerHTML`.
You should choose between setting `p` content or innerHTML, you can't do both at the same time.
Note the this library is to truncate text, not html, and angular-linky will transform text into html, truncating that could result on invalid html.

**Comment by cikcoh** [comment]
Thanks a lot man..it's working again. I just set all pipe to innerHtml. Good explanation, really helpful.
