### ISSUE TITLE
Not working after Angular 9 upgrade

### ISSUE THREAD

**Issue by vaidhys** [yellowspot/ng2-truncate#45]
Not working after Angular 9 upgrade

**Comment by mgrunberg** [comment]
Thanks for let us know.

[Live demo](https://embed.plnkr.co/d3JiQCw756OEjS0HkVuY) was updated to angular 9 and works fine with version 1.5.1.

Can you provide more info?

**Comment by grbalmeida** [comment]
![truncateng](https://user-images.githubusercontent.com/40013090/74489011-b9608380-4ea2-11ea-82cc-608a9e3cef86.JPG)

Same error here after update to Angular 9

**Comment by grbalmeida** [comment]
https://www.npmjs.com/package/ng2-truncate

The error happened because I was using the lib above
