### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by anmuel** [yellowspot/ng2-truncate#51]
I was a bit unsure wether I can use this package in a project of mine, as the [npmjs.com package page](https://www.npmjs.com/package/@yellowspot/ng-truncate) shows License "none".
Do I have something to consider? Can we add a LICENCE file / information to the package.json?

**Comment by cristianstu** [comment]
Yes! you can use it.

We should add a license indeed.

**Comment by anmuel** [comment]
so it's MIT now I suppose :)

**Comment by mgreg89** [comment]
Hello :) 

Could you please publish the license information and the updated package.json via npm? That would be very helpful for using this great pipe within projects with automated license scanning :)

Thank you very much!

**Comment by cristianstu** [comment]
@mgreg89 totally forgot about it, thanks!

Done!

**Comment by mgreg89** [comment]
Wow, that was fast! Thank you 🤗
